spring.application.name=FinazApp
server.port=8862

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://d063c13uibrs73e6it7g-a.oregon-postgres.render.com/usuarios_ay7e
spring.datasource.username=alex
spring.datasource.password=wuO1FjowW3ymyz91uVfjjGSGWmqb1aH1
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret.key=32a812ae37325ef1ecb0470f7205e7fdcb038aacef44ad631fdc9186179de32c
jwt.time.expiration=2000000000