spring.application.name=FinazApp
server.port=8862

spring.datasource.url=jdbc:postgresql://localhost:5432/Sprint1
spring.datasource.username=postgres
spring.datasource.password=edding350
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true